version: "3.8"

services:
  weather-ms:
    build: .
    container_name: weather-ms
    ports:
      - "8888:8888"
    environment:
      - API_KEY=${API_KEY}
    command: python main.py
    volumes:
      - .:/app
